### ISSUE TITLE
Assembly Program

### ISSUE THREAD

**Issue by cameronbourke** [sauravyash/COMP3211Project#3]
### Description
We need to write an assembly program using our `ISA` that processes a `record` from the "network".

**Reference Pseudo-code**
![image](https://user-images.githubusercontent.com/7464366/163357927-897a5e5f-c76e-429c-b9a9-3d5556bc2eef.png)

### Tasks
- [ ] Implement the initialisation
- [ ] Implement polling
- [ ] Implement updating the vote count
- [ ] Implement tag generation
