### ISSUE TITLE
ISA Design

### ISSUE THREAD

**Issue by cameronbourke** [sauravyash/COMP3211Project#4]
### Description
We need to design an ISA that can be used to implement the record processing in software, as opposed to hardware. Some suggested instructions are:
![image](https://user-images.githubusercontent.com/7464366/163360913-3b307b5a-3650-4388-992b-c18bb05037ad.png)

### Proposed Design
TODO

### Tasks
- [ ] Create initial draft
- [ ] Impl `addi` @christ12938
- [x] Impl `add`
- [ ] Impl `srlv` @christ12938 
- [ ] Impl `sllv` @christ12938 
- [ ] Impl `sub` @christ12938 
- [x] Impl `lw`
- [x] Impl `sw`
- [x] Impl `rolb`
- [x] Impl `xorb`
- [x] Impl `j`
- [x] Impl `bne`
- [x] Impl `beq`
